---
- name: Install Apache HTTP Server Only
  hosts: all
  become: yes
  gather_facts: yes
    
  tasks:
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: present
    
    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: yes
    
    - name: Open firewall for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes

# Inventory
[webservers]
demoweb01 ansible_host=172.31.5.102 ansible_user=ec2-user ansible_ssh_private_key_file=/root/demousrkey.pem
demoweb02 ansible_host=172.31.10.81 ansible_user=ec2-user ansible_ssh_private_key_file=/root/demousrkey.pem

[dbservers]
demodb01 ansible_host=172.31.6.107 ansible_user=ec2-user ansible_ssh_private_key_file=/root/demousrkey.pem

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
